### ISSUE TITLE
Release with types

### ISSUE THREAD

**Issue by bminixhofer** [developit/web-worker#13]
Hi. Thanks for this library!

Would it be possible to do a patch release including the types from https://github.com/developit/web-worker/commit/7a367d2ea10e34ab2b9eca8560c24a14bc812b5e? 

I want to use `web-worker` with Typescript but I noticed that this fix was done on Apr 25th while the latest release v1.0.0 was done on Apr 17th so it doesn't include types.

**Comment by marvinhagemeister** [comment]
FYI: PR #18 is required to get typings to work.

**Comment by developit** [comment]
Thanks @marvinhagemeister
